### ISSUE TITLE
「危」暴力攻入学校的后台系统 - 埃拉の个人博客

### ISSUE THREAD

**Issue by ElaBosak233** [ElaBosak233/e23.dev#23]
https://e23.in/2021/05/29/%E6%9A%B4%E5%8A%9B%E6%94%BB%E5%87%BB%E5%AD%A6%E6%A0%A1%E7%9A%84%E5%90%8E%E5%8F%B0%E7%B3%BB%E7%BB%9F/ 

 危险操作，请酌情采用，本文仅提供暴力破解的思路，从一个实例中学习

本文不是专门针对学校，只是因为学校的服务器防御力比较高，在受到攻击的时候会很自觉地返回 服务器压力过大，即使从理论上来讲给埃拉两三年的时间可以破解进去，但是学校的响应速度也真的是感人，是个人都没有这种耐心（毕竟我没有那么多钱去应酬云服务器，而且浪...

**Comment by MerakW** [comment]
在科创空间目睹全程
我直接好家伙

**Comment by LeSnow-Ye** [comment]
然后我们学校连官网都没有
